#!/bin/sh

set -e

if ! git status | grep -Fq '(working directory clean)' ; then
    echo 'working directory unclean'
    exit 1
fi

head=`git rev-parse HEAD`

cp -Rl ../dweeb/src/dweeb .
git add .
git commit -m 'heroku deployment'

git push -f heroku HEAD:master

git reset --hard ${head}
git clean -fd
